### ISSUE TITLE
Create readme with basic dev setup

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/youthtechprogram#1]
Please! :smiley:

**Comment by thekaveman** [comment]
Just a heads up - I can't get this site to run locally on Windows. 

I'm running into the issues described here: https://gist.github.com/luislavena/f064211759ee0f806c88
Pretty gnarly, not sure that we need to do anything to the repo itself though.

**Comment by allejo** [comment]
Can you run CityNet locally on Windows?

**Comment by thekaveman** [comment]
That's the weird thing, CityNet worked just fine!

**EDIT**

I should note that `bundle install` did make changes to the `Gemfile.lock` (in CityNet) that I didn't commit, since they were Windows specific changes.

``` diff
diff --git a/Gemfile.lock b/Gemfile.lock
index c2c6676..d71827b 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -16,6 +16,7 @@ GEM
     ethon (0.9.0)
       ffi (>= 1.3.0)
     ffi (1.9.10)
+    ffi (1.9.10-x64-mingw32)
     html-proofer (3.0.6)
       activesupport (~> 4.2)
       addressable (~> 2.3)
@@ -55,6 +56,8 @@ GEM
       sass (>= 3.3)
     nokogiri (1.6.7.2)
       mini_portile2 (~> 2.0.0.rc2)
+    nokogiri (1.6.7.2-x64-mingw32)
+      mini_portile2 (~> 2.0.0.rc2)
     parallel (1.8.0)
     rb-fsevent (0.9.7)
     rb-inotify (0.9.7)
@@ -72,6 +75,7 @@ GEM

 PLATFORMS
   ruby
+  x64-mingw32

```

**Comment by allejo** [comment]
Seems bundler has a history of lacking proper cross-platform support: https://github.com/bundler/bundler/issues/4517

**Comment by allejo** [comment]
So since this issue was reopened, there's a new option that we can try out:

```
bundle lock --add-platform x64-mingw32
```

However, I'm curious to see if a Gemfile lock is even required for developing on this repo. The only dependency is always the latest github-pages gem and GitHub pages doesn't use the lock file, so I don't see it serving any other purpose than another file to commit.

**Comment by thekaveman** [comment]
I'm all for getting rid of the lock file if it's not really needed. Anything that removes friction from cross-platform development.

**Comment by allejo** [comment]
👍
